### ISSUE TITLE
Fails with poetry-core 1.6.0

### ISSUE THREAD

**Issue by brandonchinn178** [celsiusnarhwal/poetry-source-env#1]
Getting the following error:
```
  ModuleNotFoundError

  No module named 'poetry.core.toml'

  at ~/.lydev/poetry/venv/lib/python3.8/site-packages/poetry_source_env/plugin.py:7 in <module>
        3│ from os.path import expandvars
        4│
        5│ from cleo.io.io import IO
        6│ from dict_deep import deep_get
    →   7│ from poetry.core.toml.file import TOMLFile
        8│ from poetry.plugins.plugin import Plugin
        9│ from poetry.poetry import Poetry
       10│ from poetry.repositories.legacy_repository import LegacyRepository
       11│ from pydantic import BaseSettings, validate_arguments
```

That module seems to have been deleted in poetry-core 1.6.0, bundled with poetry 1.5.0: https://github.com/python-poetry/poetry-core/pull/483

**Comment by brandonchinn178** [comment]
Downgrading to poetry 1.4, I'm getting
```
Only one repository can be the default
```

**Comment by celsiusnarhwal** [comment]
Hi, thanks for reporting. I'l look into this when I get a chance. 👍🏾

**Comment by brandonchinn178** [comment]
> What do you mean by this?

Running `poetry self add poetry-source-env` fetches `poetry-source-env` from files.pythonhosted.com, not the repos configured in env vars.

This makes sense, because poetry doesnt know to use the env vars before installing poetry-source-env. But I'm just pointing this out as a problem poetry-source-env might want to take a look at; e.g. in the original poetry issue, someone pointed out a solution using `~/.config/poetry/pyproject.toml`

**Comment by celsiusnarhwal** [comment]
> Running poetry self add poetry-source-env fetches poetry-source-env from files.pythonhosted.com, not the repos configured in env vars.

As far as I can tell, Poetry does not load plugins when executing `poetry self` commands, so what you're asking is unfortunately impossible. If and when python-poetry/poetry#5958 is resolved Poetry will hopefully be able to do this on its own.

**Comment by celsiusnarhwal** [comment]
poetry-source-env 1.6.0 has been released, requiring Poetry 1.5.0 or later. You may need to invoke Poetry with the `--no-plugins` option in order to get around failures that could arise from temporary incompatibilities between Poetry and poetry-source-env as you update both.

If your issues persist, feel free to leave another comment here.

**Comment by brandonchinn178** [comment]
> what you're asking is impossible

That's not true, this is one way you can do it:

https://github.com/python-poetry/poetry/issues/5958#issuecomment-1479183720

The README should mention this step before running `poetry self add poetry-source-env`, in case someone wanting to use `poetry-source-env` can't access the internet at all

**Comment by celsiusnarhwal** [comment]
> That's not true, this is one way you can do it:
>
> https://github.com/python-poetry/poetry/issues/5958#issuecomment-1479183720

Minor clarification: it's impossible for poetry-source-env to accomplish.

I appreciate your suggestion, though — I'll add that information to the README.
